# Generated by Django 5.2 on 2025-05-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='file',
            field=models.FileField(max_length=255, upload_to='csv_uploads/'),
        ),
    ]
